version: "3.7"

networks:
  kafka_network:
    driver: bridge
    name: kafka_network_name

services:
  kafka:
    container_name: kafka
    image: 'bitnami/kafka:latest'
    networks:
      - kafka_network
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
    ports:
      - "9094:9094"
  create_default_topic:
    container_name: create_default_topic
    depends_on:
      - kafka
    image: 'bitnami/kafka:latest'
    entrypoint:
      kafka-topics.sh --create --topic temperatures --bootstrap-server kafka:9092
    networks:
      - kafka_network
  temperature_producer:
    container_name: temperature_producer
    depends_on:
      - kafka
      - create_default_topic
#    build:
#      context: temperature_producer
#      dockerfile: Dockerfile
    image: producer:v11
    environment:
      - JAVA_OPTS=
      - BOOTSTRAP_SERVERS=kafka:9092
      - TEMPERATURE_TOPIC_NAME=temperatures
      - EVENT_DELAY_MS=1000
      - NUMBER_OF_EVENTS=20
      - MINIMUM_TEMPERATURE=20
      - MAXIMUM_TEMPERATURE=32
      - THERMOMETER_IDENTIFIER=thermometer_2
    networks:
      - kafka_network
  postgres_db:
    image: postgres:16
    container_name: postgres_db
    environment:
      - POSTGRES_PASSWORD=s3cr3t
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - ./init_db.sql:/init_db.sql
      - ./sample_db_data.sql:/sample_db_data.sql
      - temperature_pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - kafka_network
  temperature_collector:
    container_name: temperature_collector
    depends_on:
      - postgres_db
      - kafka
      - create_default_topic
    image: collector:v10
    ports:
      - "8081:8080"
    environment:
      - JAVA_OPTS=
      - BOOTSTRAP_SERVERS=kafka:9092
      - TEMPERATURE_TOPIC_NAME=temperatures
      - SPRING_DATASOURCE_USERNAME=temperature_collector
      - SPRING_DATASOURCE_PASSWORD=sK2rPjqfufz30jT
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres_db:5432/temperature_db
      - DETECTION_ALGORITHM=timeSensitive
    networks:
      - kafka_network

volumes:
  temperature_pg_data:
    name: temperature_pg_data